modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/ImVadimush/FuryCustomTags/issues"

[[mods]]
modId="furycustomtags"
version="1.0.0"
displayName="Fury Custom Tags"
updateJSONURL="https://github.com/ImVadimush/FuryCustomTags/releases"
displayURL="https://github.com/ImVadimush/FuryCustomTags"
credits="ImVadimush"
authors="ImVadimush"
description='''
Клиентский мод для отображения твоего prefix + nickname + suffix над головой в режиме F5. Работает с LuckPerms и TAB плагинами.
'''

[[dependencies.furycustomtags]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.furycustomtags]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="CLIENT"
