modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/ImVadimush/FuryCustomTags/issues"

[[mods]]
modId="furycustomtags"
version="1.0.1"
displayName="Fury Custom Tags"
updateJSONURL="https://github.com/ImVadimush/FuryCustomTags/releases"
displayURL="https://github.com/ImVadimush/FuryCustomTags"
credits="ImVadimush"
authors="ImVadimush"
description="Client-side mod for displaying your prefix + nickname + suffix in F5 mode. Works with LuckPerms and TAB plugins."

[[dependencies.furycustomtags]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.furycustomtags]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="CLIENT"
